/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        // WinBox design system colors
        wb: {
          'title-start': '#4a7ab5',
          'title-end': '#2d5a87',
          'title-text': '#ffffff',
          'menu-bg': '#f0f0f0',
          'menu-border': '#a0a0a0',
          'sidebar-bg': '#ffffff',
          'sidebar-border': '#a0a0a0',
          'selection': '#316AC5',
          'selection-text': '#ffffff',
          'content-bg': '#c0c0c0',
          'toolbar-start': '#ffffff',
          'toolbar-end': '#e8e8e8',
          'toolbar-border': '#a0a0a0',
          'table-header-start': '#ffffff',
          'table-header-end': '#e0e0e0',
          'table-header-border': '#a0a0a0',
          'table-row-even': '#ffffff',
          'table-row-odd': '#f7f7f7',
          'table-cell-border': '#eee',
          'table-border': '#ccc',
          'status-bg': '#f0f0f0',
          'status-border': '#a0a0a0',
          'online': '#4CAF50',
          'offline': '#f44336',
          'expired': '#FF9800',
          'fup1': '#2196F3',
          'fup2': '#FF9800',
          'fup3': '#f44336',
          'danger': '#c0392b',
          'danger-hover': '#a93226',
          'border': '#a0a0a0',
          'border-inner': '#ccc',
          'border-cell': '#eee',
          'input-bg': '#ffffff',
          'input-border': '#a0a0a0',
        },
      },
      fontFamily: {
        'segoe': ['"Segoe UI"', 'Tahoma', 'Geneva', 'Verdana', 'sans-serif'],
      },
      fontSize: {
        'wb-xs': ['10px', { lineHeight: '14px' }],
        'wb-sm': ['12px', { lineHeight: '17px' }],
        'wb-base': ['13px', { lineHeight: '19px' }],
        'wb-md': ['14px', { lineHeight: '21px' }],
      },
      borderRadius: {
        'wb': '2px',
      },
    },
  },
  plugins: [],
}
