package services

import (
	"fmt"
	"log"
	"strconv"
	"sync"
	"time"

	"github.com/proisp/backend/internal/database"
	"github.com/proisp/backend/internal/models"
)

// InvoiceGenerationService auto-generates invoices for subscribers with auto_invoice=true
// before their expiry date. Runs once daily at the configured notification send time.
type InvoiceGenerationService struct {
	stopChan  chan struct{}
	wg        sync.WaitGroup
	lastRunAt time.Time
	notifMgr  *NotificationManager
}

// NewInvoiceGenerationService creates a new invoice generation service
func NewInvoiceGenerationService() *InvoiceGenerationService {
	return &InvoiceGenerationService{
		stopChan: make(chan struct{}),
		notifMgr: NewNotificationManager(),
	}
}

// Start begins the invoice generation scheduler
func (s *InvoiceGenerationService) Start() {
	s.wg.Add(1)
	go func() {
		defer s.wg.Done()
		log.Println("InvoiceGenerationService started")

		ticker := time.NewTicker(1 * time.Minute)
		defer ticker.Stop()

		for {
			select {
			case <-ticker.C:
				s.checkAndRun()
			case <-s.stopChan:
				log.Println("InvoiceGenerationService stopped")
				return
			}
		}
	}()
}

// Stop stops the invoice generation service
func (s *InvoiceGenerationService) Stop() {
	close(s.stopChan)
	s.wg.Wait()
}

// checkAndRun fires once daily at the configured notification send time
func (s *InvoiceGenerationService) checkAndRun() {
	now := getNow()
	sendHour, sendMinute := getNotificationSendTime()

	if now.Hour() != sendHour || now.Minute() != sendMinute {
		return
	}

	// Prevent double-firing within the same minute
	todayRun := time.Date(now.Year(), now.Month(), now.Day(), sendHour, sendMinute, 0, 0, now.Location())
	if !s.lastRunAt.IsZero() && s.lastRunAt.After(todayRun.Add(-1*time.Minute)) {
		return
	}
	s.lastRunAt = now

	log.Printf("InvoiceGenerationService: Running at %02d:%02d", sendHour, sendMinute)
	s.generateInvoices()
}

// generateInvoices is the core logic that creates invoices for eligible subscribers
func (s *InvoiceGenerationService) generateInvoices() {
	// Read days_before setting
	daysBefore := 7
	var pref models.SystemPreference
	if err := database.DB.Where("key = ?", "invoice_days_before_expiry").First(&pref).Error; err == nil {
		if v, err := strconv.Atoi(pref.Value); err == nil && v > 0 {
			daysBefore = v
		}
	}

	now := time.Now()
	cutoff := now.AddDate(0, 0, daysBefore)

	// Query eligible subscribers: auto_invoice=true, active, expiry within N days but not expired
	var subscribers []models.Subscriber
	if err := database.DB.
		Preload("Service").
		Preload("Reseller").
		Where("auto_invoice = ? AND status = ? AND expiry_date <= ? AND expiry_date > ? AND deleted_at IS NULL",
			true, models.SubscriberStatusActive, cutoff, now).
		Find(&subscribers).Error; err != nil {
		log.Printf("InvoiceGeneration: Failed to query subscribers: %v", err)
		return
	}

	if len(subscribers) == 0 {
		log.Printf("InvoiceGeneration: No eligible subscribers (days_before=%d)", daysBefore)
		return
	}

	created := 0
	skipped := 0

	for _, sub := range subscribers {
		// Determine billing period
		billingStart := sub.ExpiryDate
		var billingEnd time.Time
		if sub.Service != nil {
			if sub.Service.ExpiryUnit == models.ExpiryUnitMonths {
				billingEnd = billingStart.AddDate(0, sub.Service.ExpiryValue, 0)
			} else {
				billingEnd = billingStart.AddDate(0, 0, sub.Service.ExpiryValue)
			}
		} else {
			billingEnd = billingStart.AddDate(0, 0, 30)
		}

		// Dedup: skip if pending/completed invoice already exists for this billing period
		var existingCount int64
		database.DB.Model(&models.Invoice{}).
			Where("subscriber_id = ? AND billing_period_start = ? AND status IN (?, ?) AND deleted_at IS NULL",
				sub.ID, billingStart, models.PaymentStatusPending, models.PaymentStatusCompleted).
			Count(&existingCount)
		if existingCount > 0 {
			skipped++
			continue
		}

		// Determine price
		price := float64(0)
		if sub.OverridePrice {
			price = sub.Price
		} else if sub.Service != nil {
			price = sub.Service.Price
		}
		if price <= 0 {
			skipped++
			continue
		}

		// Generate unique invoice number
		invoiceNumber := s.generateInvoiceNumber()

		// Create invoice
		invoice := models.Invoice{
			InvoiceNumber:      invoiceNumber,
			SubscriberID:       sub.ID,
			ResellerID:         sub.ResellerID,
			SubTotal:           price,
			Tax:                0,
			Total:              price,
			AmountPaid:         0,
			Status:             models.PaymentStatusPending,
			DueDate:            sub.ExpiryDate,
			BillingPeriodStart: &billingStart,
			BillingPeriodEnd:   &billingEnd,
			AutoGenerated:      true,
			Notes:              "Auto-generated invoice",
		}
		if err := database.DB.Create(&invoice).Error; err != nil {
			log.Printf("InvoiceGeneration: Failed to create invoice for %s: %v", sub.Username, err)
			continue
		}

		// Create invoice item
		serviceName := "Internet Service"
		if sub.Service != nil {
			serviceName = sub.Service.Name
		}
		item := models.InvoiceItem{
			InvoiceID:   invoice.ID,
			Description: fmt.Sprintf("%s — %s to %s", serviceName, billingStart.Format("2006-01-02"), billingEnd.Format("2006-01-02")),
			Quantity:    1,
			UnitPrice:   price,
			Total:       price,
		}
		database.DB.Create(&item)

		// Send notification
		s.sendInvoiceNotification(sub, invoice, price)

		created++
		log.Printf("InvoiceGeneration: Created invoice %s for %s ($%.2f, due %s)",
			invoiceNumber, sub.Username, price, sub.ExpiryDate.Format("2006-01-02"))
	}

	log.Printf("InvoiceGeneration: Done — created=%d, skipped=%d", created, skipped)
}

// generateInvoiceNumber creates a unique invoice number: INV-YYYY-NNNN
func (s *InvoiceGenerationService) generateInvoiceNumber() string {
	year := time.Now().Year()

	// Count existing invoices this year for sequential numbering
	var count int64
	database.DB.Model(&models.Invoice{}).
		Where("invoice_number LIKE ?", fmt.Sprintf("INV-%d-%%", year)).
		Count(&count)

	return fmt.Sprintf("INV-%d-%04d", year, count+1)
}

// sendInvoiceNotification sends notification via configured channels
func (s *InvoiceGenerationService) sendInvoiceNotification(sub models.Subscriber, invoice models.Invoice, amount float64) {
	data := &NotificationData{
		SubscriberID:  sub.ID,
		Username:      sub.Username,
		FullName:      sub.FullName,
		Email:         sub.Email,
		Phone:         sub.Phone,
		ExpiryDate:    sub.ExpiryDate.Format("2006-01-02"),
		DaysRemaining: sub.DaysRemaining(),
		InvoiceNumber: invoice.InvoiceNumber,
		Amount:        fmt.Sprintf("$%.2f", amount),
	}
	if sub.Service != nil {
		data.ServiceName = sub.Service.Name
	}

	if err := s.notifMgr.SendNotification(NotifyInvoice, data); err != nil {
		log.Printf("InvoiceGeneration: Notification failed for %s: %v", sub.Username, err)
	}
}
